name: build ci container

on:
  push:
    branches:
      - 'master'
      - 'container'
    paths:
      - 'test/Dockerfile'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: rauc-ci
        tags: latest
        dockerfiles: |
          ./test/Dockerfile
    - id: push-to-github
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io/${{ github.repository }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - run: echo "Image pushed to ${{ steps.push-to-github.outputs.registry-paths }}"
