name: scan-build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:unstable
      options: --user=root
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND='noninteractive' apt-get install -qy meson libtool libglib2.0-dev libcurl3-dev libssl-dev libdbus-1-dev libjson-glib-dev libfdisk-dev libnl-genl-3-dev dbus-x11 clang-tools

    - name: Inspect environment
      run: |
        whoami
        gcc --version
        ls -la /usr/bin/clang*

    - uses: actions/checkout@v4

    - name: Run meson
      run: |
        meson setup build

    - name: Run scan-build
      run: |
        SCANBUILD=$(pwd)/scan-build-wrapper.sh ninja -C build scan-build

    - name: Upload scan-build report
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: scan-build-report
        path: build/meson-logs/scanbuild/*
